spring:
  application:
    name: product-service  # Service name for discovery
  datasource:
    url: jdbc:mysql://localhost:3306/productservice
    username: root
    password: Lunardefectvs4*
  jpa:
    hibernate:
      ddl-auto: update
  cloud:
    consul:
      discovery:
        enabled: true
        register: true
        service-name: product-service  # Name registered in Consul

server:
  port: 8082  # Port for product-service
  cd AllProjectsRepo
